### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by aozmekik** [kibok90/cvpr2018-hnd#1]
![screenshot](https://user-images.githubusercontent.com/32572999/60897307-8604a900-a270-11e9-8d1b-2a3af5df26b6.png)

I consistently get `MemoryError`. As seen in picture above, I had `batch_size=1`.
And I've changed `transforms.Resize(256)` to  `transforms.Resize(16)` on **utils.py**.( _line 31_) 

Additionaly, besides the data you share, Is there any other tiny dataset that I can quickly try in my machine? 

**Specs**

>  Memory 15,6 GiB
>  Processor: Intel® Core™ i7-7700 CPU @ 3.60GHz × 8 
>  Graphics: GeForce GTX 1080/PCIe/SSE2
>  OS = 64-bit

**Comment by kibok90** [comment]
Hi Ahmed,
The code loads all ResNet features to the memory for fast training. It requires ~ 32 GiB of memory to run training script with test. (`batch_size` has a minor effect on the memory usage, and `extract_features()` in `utils.py` is simply not used because you already have ResNet features.)

To reduce the memory requirement, you can separate the training and test stage.
First, you may not perform test when training, by removing `-test` flag in `train.sh`.
After training, for test, you can set `dtypes = ['val', 'known', 'novel']` in
https://github.com/kibok90/cvpr2018-hnd/blob/master/train.py#L128
and re-run `train.sh` with `-test` flag. This will perform test only, once you have a converged model.
(`dtypes` are types of datasets to be loaded.)

On the other hand, you can use AWA or CUB dataset for quick training & test. (I just confirmed that ResNet features of these datasets are still downloadable.)
